### ISSUE TITLE
✨ [Feat] 공부 방법 관련 API 구현

### ISSUE THREAD

**Issue by Eunjin3395** [Timify-repo/Timify-server#29]
## 📝 기능 개요

공부 방법 등록/조회/수정 API 구현

## ✅ Todo
- [x] 공부 방법 등록 API 구현
- [x] 공부 방법 조회 API 구현
- [x] 공부 방법 수정 API 구현
- [x] Validation
- [x] Swagger 명세
